"""Extraction output schema and validation.

Mirrors docs/ontology.md: systems -> System, symptoms -> Symptom, issues -> Issue,
possible_causes -> Cause, support_actions -> SupportAction. `is_technical_incident`
is pipeline metadata and never enters the graph.
"""

from collections.abc import Mapping
from typing import Any

SUPPORT_ACTION_TYPES = (
    "request_information",
    "troubleshooting",
    "workaround",
    "status_update",
    "resolution",
    "general_response",
)

LIST_FIELDS = ("systems", "symptoms", "issues", "possible_causes")
# Fields the LLM produces. `ticket_id` is attached by code, never generated by the model.
MODEL_FIELDS = ("is_technical_incident", *LIST_FIELDS, "support_actions")
RECORD_FIELDS = ("ticket_id", *MODEL_FIELDS)

_STRING_LIST = {"type": "array", "items": {"type": "string"}}

# JSON Schema sent to the API as the output format (constrains the model's output).
# `validate_extraction` re-checks everything locally; the API constraint is not trusted alone.
MODEL_OUTPUT_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "is_technical_incident": {"type": "boolean"},
        "systems": _STRING_LIST,
        "symptoms": _STRING_LIST,
        "issues": _STRING_LIST,
        "possible_causes": _STRING_LIST,
        "support_actions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "action": {"type": "string"},
                    "action_type": {"type": "string", "enum": list(SUPPORT_ACTION_TYPES)},
                },
                "required": ["action", "action_type"],
                "additionalProperties": False,
            },
        },
    },
    "required": list(MODEL_FIELDS),
    "additionalProperties": False,
}


def _check_string_list(record: Mapping[str, Any], field: str) -> list[str]:
    value = record[field]
    if not isinstance(value, list):
        return [f"{field}: expected a list, got {type(value).__name__}"]
    errors = []
    for index, item in enumerate(value):
        if not isinstance(item, str):
            errors.append(f"{field}[{index}]: expected a string, got {type(item).__name__}")
        elif not item.strip():
            errors.append(f"{field}[{index}]: blank string")
    return errors


def _check_support_action(action: Any, index: int) -> list[str]:
    prefix = f"support_actions[{index}]"
    if not isinstance(action, Mapping):
        return [f"{prefix}: expected an object, got {type(action).__name__}"]
    errors = []
    unexpected = sorted(set(action) - {"action", "action_type"})
    if unexpected:
        errors.append(f"{prefix}: unexpected keys {unexpected}")
    text = action.get("action")
    if not isinstance(text, str) or not text.strip():
        errors.append(f"{prefix}.action: expected a non-blank string")
    action_type = action.get("action_type")
    if action_type not in SUPPORT_ACTION_TYPES:
        errors.append(f"{prefix}.action_type: {action_type!r} is not one of {list(SUPPORT_ACTION_TYPES)}")
    return errors


def validate_extraction(
    record: Any, *, expected_ticket_id: str, has_answer: bool
) -> list[str]:
    """Return all schema/consistency errors for one extraction record (empty list = valid).

    `has_answer` is whether the source ticket has a support answer. Without one there is
    nothing to extract support actions from, so any listed action would be invented.
    """
    if not isinstance(record, Mapping):
        return [f"record: expected an object, got {type(record).__name__}"]

    errors = []
    missing = [field for field in RECORD_FIELDS if field not in record]
    if missing:
        errors.append(f"missing fields {missing}")
    unexpected = sorted(set(record) - set(RECORD_FIELDS))
    if unexpected:
        errors.append(f"unexpected fields {unexpected}")

    if "ticket_id" in record and record["ticket_id"] != expected_ticket_id:
        errors.append(f"ticket_id: {record['ticket_id']!r} does not match the source ticket")

    if "is_technical_incident" in record and not isinstance(record["is_technical_incident"], bool):
        errors.append(
            f"is_technical_incident: expected a boolean, got {type(record['is_technical_incident']).__name__}"
        )

    for field in LIST_FIELDS:
        if field in record:
            errors.extend(_check_string_list(record, field))

    if "support_actions" in record:
        actions = record["support_actions"]
        if not isinstance(actions, list):
            errors.append(f"support_actions: expected a list, got {type(actions).__name__}")
        else:
            for index, action in enumerate(actions):
                errors.extend(_check_support_action(action, index))
            if actions and not has_answer:
                errors.append("support_actions: listed although the ticket has no support answer")

    return errors
